#RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
#RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

#RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

#RUN apt-get update
#RUN apt-get install -y --no-install-recommends \
#        python-dev \
#        nodejs \
#        yarn
