version: '3.1'

services:
    mysql:
        container_name: $MYSQL_CONTAINER
        image: $MYSQL_IMAGE
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            LANG: C.UTF-8
        volumes:
            - "./data/db/mysql:/var/lib/mysql:delegated"
            - "./mysql-init-script:/docker-entrypoint-initdb.d:delegated"
            - "./log/mysql/:/var/log/mysql/:delegated"
    webapp:
        container_name: $APP_CONTAINER
        image: $APP_IMAGE
        volumes:
            - "./webroot/:/var/www/html/:delegated"
            - "./log/apache2/access.log:/var/log/apache2/access.log:delegated"
            - "./log/apache2/error.log:/var/log/apache2/error.log:delegated"
        environment:
            DOCKERIZED: 1
            APP_ROOT: $APP_ROOT
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_USER: $MYSQL_USER
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_HOST: $MYSQL_CONTAINER
            WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
            LANG: C.UTF-8
            DEBUG: $DEBUG
        depends_on:
            - mysql
