FROM mysql:5.6

ARG USERID
ARG GROUPID

ENV DEBIAN_FRONTEND noninteractive

RUN userdel mysql

RUN bash -c 'if [[ $(getent group $GROUPID | cut -d: -f1) == "" ]]; then groupadd -g $GROUPID mysql; else groupmod --new-name mysql $(getent group $GROUPID | cut -d: -f1); fi'
RUN bash -c 'if [[ $(id -u mysql 2>/dev/null) == "" ]]; then useradd -r -g mysql -u $USERID mysql; else usermod -u $USERID mysql; fi'

RUN chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
