version: '3.1'

services:
    mysql:
        restart: always
        container_name: $MYSQL_CONTAINER
        image: $MYSQL_IMAGE
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            LANG: C.UTF-8
        volumes:
            - "./data/db/mysql:/var/lib/mysql:cached"
            - "./mysql-init-script:/docker-entrypoint-initdb.d:cached"
            - "./log/mysql/error.log:/var/log/mysql/error.log:cached"
        ports: [ $MYSQL_PORT_MAP ]
    webapp:
        restart: always
        container_name: $APP_CONTAINER
        image: $APP_IMAGE
        ports: [ $APP_PORT_MAP ]
        volumes:
            - "./webroot/:/var/www/html/:cached"
            - "./log/apache2/access.log:/var/log/apache2/access.log:cached"
            - "./log/apache2/error.log:/var/log/apache2/error.log:cached"
        environment:
            APP_ROOT: $APP_ROOT
            MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_USER: $MYSQL_USER
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_HOST: $MYSQL_CONTAINER
            LANG: C.UTF-8
        depends_on:
            - mysql
