FROM php:7.0-apache

ENV DEBIAN_FRONTEND noninteractive

ARG USERID
ARG GROUPID

RUN groupadd -g $GROUPID mapped || groupmod -n mapped $(getent group $GROUPID | cut -d: -f1)
RUN useradd \
      --uid $USERID \
      --gid $GROUPID \
      --home-dir /var/www/html/ \
      mapped
RUN chown -R mapped: /var/www/html/

ENV APACHE_RUN_USER mapped
ENV APACHE_RUN_GROUP mapped

RUN apt-get update
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libmagickwand-dev \
        libncurses5-dev 

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-configure mcrypt
RUN docker-php-ext-install -j$(nproc) gd mcrypt opcache mysqli pdo_mysql

RUN a2enmod rewrite headers expires


