RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr
RUN docker-php-ext-install -j $(( $(nproc) * 2 )) mysqli

RUN (cd ~/ && (curl -s https://getcomposer.org/installer | php)) \
    && mv ~/composer.phar /usr/bin/composer \
    && composer global require "fxp/composer-asset-plugin:~1.1.2" --no-plugins
