ARG VERS_COMPOSER

RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr
RUN docker-php-ext-install -j $(( $(nproc) * 2 )) mysqli

RUN (cd ~/ && (curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=$VERS_COMPOSER))

RUN composer global require "fxp/composer-asset-plugin:~1.1.2" --no-plugins
