version: '3.1'

services:
    webapp:
        container_name: $APP_CONTAINER
        image: $APP_IMAGE
        volumes:
            - "./webroot/:/var/www/html/:delegated"
            - "./config/:/tmp/config:delegated"
        environment:
            DOCKERIZED: 1
            APP_ROOT: $APP_ROOT
            LANG: C.UTF-8
            DEBUG: $DEBUG
