# IMAGE_TAG node:18
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
        curl \
        gnupg \
        yarn \
        gulp \
        build-essential

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 18

RUN mkdir -p $NVM_DIR && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | NVM_DIR=$NVM_DIR bash

ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    npm install -g npm