# IMAGE_TAG apache:latest
FROM ubuntu:18.04

ENV TZ=Europe/Minsk
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    apache2 \
    apt-transport-https \
    apt-utils \
    gnupg \
    software-properties-common

RUN apt-get install -y --no-install-recommends mysql-client || apt-get install -y --no-install-recommends default-mysql-client

RUN a2dismod mpm_prefork
RUN a2enmod rewrite expires mpm_event proxy proxy_fcgi ssl http2