# IMAGE_TAG node:10
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
        curl \
        gnupg

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get install -y \
        nodejs \
        yarn \
        gulp \
        build-essential

RUN npm update npm -g