# IMAGE_TAG node:16
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y \
        curl \
        gnupg

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -

RUN apt-get install -y \
        nodejs \
        yarn \
        gulp

RUN npm update npm -g
