# IMAGE_TAG node:10
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
        curl \
        gnupg

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && source ~/.bashrc && nvm install 10

RUN apt-get install -y \
        yarn \
        gulp \
        build-essential

RUN npm update npm -g